{
 "title": "Mission 2",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "In-Memory Series - Mimir Ingester",
   "type": "timeseries",
   "description": "The number of timeseries currently in memory for the Mimir Ingester.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cortex_ingester_memory_series{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mythical_db_request_count_total cardinality",
   "type": "timeseries",
   "description": "Someone noticed our Mimir database running out of memory, and a particular metric is the culprit. We should get this down much closer to 0 and save Mimir!",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(mythical_db_request_count_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All mythical_db_request_count_totals",
   "type": "timeseries",
   "description": "An engineer narrowed down the cardinality explosion to this metric",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, mythical_db_request_count_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}