{
 "title": "Mythical Service Logs",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "# Mythical Service Logs",
   "type": "timeseries",
   "description": "The rate of log lines being sent by the Mythical services.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (rate({service_name=~\"mythical-.*\"}[$__auto]))"
    }
   ]
  },
  {
   "title": "Requester Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"mythical-requester\"}"
    }
   ]
  },
  {
   "title": "Server Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"mythical-server\"}"
    }
   ]
  }
 ]
}