version: "3"
volumes:
  grafana:
  postgres:
services:
  # Grafana agent batches and processes traces sent to it, generating metrics
  # and auto-logs from those traces.
  # Includes Metrics, Logs and Traces
  agent:
    image: grafana/agent:v0.34.3
    ports:
      - "12347:12345"
      - "12348:12348"
      - "6832:6832"
      - "55679:55679"
    volumes:
      - "./agent/config-cloud-configured.yaml:/etc/agent/agent.yaml"
    command: [
      "-config.file=/etc/agent/agent.yaml",
      "-server.http.address=0.0.0.0:12345",
    ]

  # A RabbitMQ queue used to send message between the requester and the server microservices.
  mythical-queue:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_running
      interval: 5s
      timeout: 30s
      retries: 10

  # A postgres DB used to store data by the API server microservice.
  mythical-database:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_PASSWORD: "mythical"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  # A microservice that makes requests to the API server microservice. Requests are also pushed onto the mythical-queue.
  mythical-requester:
    build:
      context: ./source
      dockerfile: docker/Dockerfile
      args:
        SERVICE: mythical-beasts-requester
    depends_on:
      - mythical-queue
      - mythical-server
    ports:
      - "4001:4001"
    environment:
      - NAMESPACE=production
      - LOGS_TARGET=https://${GRAFANA_LOGS_USERNAME}:${GRAFANA_LOGS_API_KEY}@${GRAFANA_LOGS_HOST}/loki/api/v1/push
      - TRACING_COLLECTOR_HOST=agent
      - TRACING_COLLECTOR_PORT=4317
      - OTEL_EXPORTER_OTLP_TRACES_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=ip=1.2.3.4

  # The API server microservice.
  # It writes logs directly to the Loki service, exposes metrics for the Prometheus
  # service and sends traces to the Grafana Agent instance.
  mythical-server:
    build:
      context: ./source
      dockerfile: docker/Dockerfile
      args:
        SERVICE: mythical-beasts-server
    ports:
      - "4000:4000"
      - "80:80"
    depends_on:
      - mythical-database
    environment:
      - NAMESPACE=production
      - LOGS_TARGET=https://${GRAFANA_LOGS_USERNAME}:${GRAFANA_LOGS_API_KEY}@${GRAFANA_LOGS_HOST}/loki/api/v1/push
      - TRACING_COLLECTOR_HOST=agent
      - TRACING_COLLECTOR_PORT=4317
      - OTEL_EXPORTER_OTLP_TRACES_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=ip=1.2.3.5

  # A microservice that consumes requests from the mythical-queue
  mythical-recorder:
    build:
      context: ./source
      dockerfile: docker/Dockerfile
      args:
        SERVICE: mythical-beasts-recorder
    depends_on:
      - mythical-queue
    ports:
      - "4002:4002"
    environment:
      - NAMESPACE=production
      - LOGS_TARGET=https://${GRAFANA_LOGS_USERNAME}:${GRAFANA_LOGS_API_KEY}@${GRAFANA_LOGS_HOST}/loki/api/v1/push
      - TRACING_COLLECTOR_HOST=agent
      - TRACING_COLLECTOR_PORT=4317
      - OTEL_EXPORTER_OTLP_TRACES_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=ip=1.2.3.5
