name: grafana-intro-to-mltp-cloud
volumes:
  grafana:
  postgres:
services:
  # Grafana Alloy batches and processes traces sent to it, generating
  # auto-logs from those traces.
  # Includes Metrics, Logs, Traces and Profiles.
  alloy:
    image: grafana/alloy:v1.17.0@sha256:41c41849989b7e054ccbadc17938ee1e5592fe26bfbc56ef3ffc109c0b0b2739
    ports:
      - "12347:12345"
      - "12348:12348"
      - "12350:12350"
      - "6832:6832"
      - "55679:55679"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - "./alloy/config.alloy:/etc/alloy/config.alloy"
      - "./alloy/endpoints-cloud.json:/etc/alloy/endpoints.json"
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--stability.level=public-preview",
      "/etc/alloy/config.alloy",
    ]

  # A RabbitMQ queue used to send message between the requester and the server microservices.
  mythical-queue:
    image: rabbitmq:management@sha256:ffd1b50c522ad20172ffd6716a2f41db375c7269560c8f3fb9a694e210ef0852
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_running
      interval: 5s
      timeout: 30s
      retries: 10

  # A postgres DB used to store data by the API server microservice.
  mythical-database:
  mythical-database:
    image: postgres:18.4@sha256:a02db8cac496f15b094798a38254f14d6e00741f709360e5e00bb6668ea31636
    restart: always
    environment:
      POSTGRES_PASSWORD: "mythical"
    volumes:
      - "postgres:/var/lib/postgresql"
    ports:
      - "5432:5432"

  # A microservice that makes requests to the API server microservice. Requests are also pushed onto the mythical-queue.
  mythical-requester:
    #build:
    #  context: ./source
    #  dockerfile: docker/Dockerfile
    #  args:
    #    SERVICE: mythical-beasts-requester
    image: ghcr.io/grafana/intro-to-mltp:mythical-beasts-requester-latest@sha256:7013d060cd092dd1c928371fbea09d361fd1137907b9b6089e15615f5f5f3533
    restart: always
    depends_on:
      mythical-queue:
        condition: service_healthy
      mythical-server:
        condition: service_started
    ports:
      - "4001:4001"
    environment:
      - NAMESPACE=production
      - LOGS_TARGET=http://alloy:3100/loki/api/v1/push
      - TRACING_COLLECTOR_HOST=alloy
      - TRACING_COLLECTOR_PORT=4317
      - PROFILE_COLLECTOR_HOST=alloy
      - PROFILE_COLLECTOR_PORT=4040
      - OTEL_EXPORTER_OTLP_TRACES_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=ip=1.2.3.4

  # React frontend for the mythical beasts management system
  mythical-frontend:
    #build:
    #  context: ./source/mythical-beasts-frontend
    #  dockerfile: Dockerfile
    #  args:
    #    - REACT_APP_API_URL=/api
    # By default, this will try and send to Alloy instead of Grafana Cloud Frontend.
    image: ghcr.io/grafana/intro-to-mltp:mythical-beasts-frontend-latest@sha256:e92da1f06562dabd0b2a18eec3ec36390382699547d177ee542fbec31f8673c5
    restart: always
    depends_on:
      mythical-server:
        condition: service_started
      alloy:
        condition: service_started
    ports:
      - "3001:80"


  # The API server microservice.
  # It writes logs directly to the Loki service, exposes metrics for the Prometheus
  # service and sends traces to the Grafana Alloy instance.
  mythical-server:
    #build:
    #  context: ./source
    #  dockerfile: docker/Dockerfile
    #  args:
    #    SERVICE: mythical-beasts-server
    image: ghcr.io/grafana/intro-to-mltp:mythical-beasts-server-latest@sha256:359afe4e8eaffa3bf1e84afea55456c96cc443aca76c5fc6f72adf1f69f5e183
    restart: always
    ports:
      - "4000:4000"
      - "80:80"
    depends_on:
      - mythical-database
    environment:
      - NAMESPACE=production
      - LOGS_TARGET=http://alloy:3100/loki/api/v1/push
      - TRACING_COLLECTOR_HOST=alloy
      - TRACING_COLLECTOR_PORT=4317
      - PROFILE_COLLECTOR_HOST=alloy
      - PROFILE_COLLECTOR_PORT=4040
      - OTEL_EXPORTER_OTLP_TRACES_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=ip=1.2.3.5
      # By default, this will try and send Faro data to the local Alloy instance.
      # For Grafana Cloud, set FARO_ENDPOINT to your Grafana Cloud Frontend endpoint, and set
      # USE_GRAFANA_CLOUD to true.
      - FARO_ENDPOINT=http://localhost:12350/collect
      - USE_GRAFANA_CLOUD=false

  # A microservice that consumes requests from the mythical-queue
  mythical-recorder:
    #build:
    #  context: ./source
    #  dockerfile: docker/Dockerfile
    #  args:
    #    SERVICE: mythical-beasts-recorder
    image: ghcr.io/grafana/intro-to-mltp:mythical-beasts-recorder-latest@sha256:00010860619f5887b4b144f499a9a84c9dc9df39ee7b2221d56e8315b8d4e91f
    restart: always
    depends_on:
      mythical-queue:
        condition: service_healthy
    ports:
      - "4002:4002"
    environment:
      - NAMESPACE=production
      - LOGS_TARGET=http://alloy:3100/loki/api/v1/push
      - TRACING_COLLECTOR_HOST=alloy
      - TRACING_COLLECTOR_PORT=4317
      - PROFILE_COLLECTOR_HOST=alloy
      - PROFILE_COLLECTOR_PORT=4040
      - OTEL_EXPORTER_OTLP_TRACES_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=ip=1.2.3.5
